# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  FILES:
    sh: gfind -type f -maxdepth 1 -name "NLNAM*.md" -printf "%P\n"
  MAIN_OPTIONS: "--allow-local-files"
  METADATA: "--title 'NLNAM: A Home for Network Automation in the Netherlands'
    --author 'Bart Dorlandt' --keywords 'network automation, meetup,
    netherlands, nlnam, netdevops' --description 'A lightning talk introducing
    the NL Network Automation Meetup (NLNAM) and how to get involved.'"
  OUTPUT_DIR: "presentation"

tasks:
  default: task -l --sort none

  mkdir:presentation:
    desc: Create presentation directory if it doesn't exist
    internal: true
    status:
      - test -d {{.OUTPUT_DIR}}
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}

  export:pdf:
    desc: Export the presentation to PDF
    deps: [mkdir:presentation]
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}} --pdf {{.METADATA}}"
    cmds:
      - for:
          var: FILES
        cmd: marp {{.OPTIONS}} -o {{.OUTPUT_DIR}}/{{.ITEM | replace ".md" ".pdf"}} {{.ITEM}}

  export:pptx:
    desc: Export the presentation to PPTX
    deps: [mkdir:presentation]
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}} --pptx {{.METADATA}}"
    cmds:
      - for:
          var: FILES
        cmd: marp {{.OPTIONS}} -o {{.OUTPUT_DIR}}/{{.ITEM | replace ".md" ".pptx"}} {{.ITEM}}

  present:
    desc: Present the presentation
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}}"
    cmds:
      - open http://localhost:8080/
      - marp -s {{.OPTIONS}} .
